# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d59ef1c7e89619f625165c1a216c7ebbc108e59255a305f730d74d5ef99033afaa62b8d9a97c5d0280cb702c27c49163cc50e3014a4396f59ffd21a08bd1b22f

test:
  secret_key_base: e44ea065e0d436ebf8e7fa36a2d916804749eeb87e0e64702121339b5317b4c919618ed3eff8120d1cb2bd9079a066869f02448599f611ebe2b65d6f665077d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
